name: stack_page_view
description: You can use the PageView keeping position of items in Android and IOS
version: 0.0.1
homepage: https://github.com/jinhan38/stack_page_view

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
